# Platform: Windows
# This makefile is is autogenerated by saucer
# Modifying the makefile can break it, use autogeneration for it
# Github: https://github.com/inugami-dev64/saucer
CC = gcc
CXX = g++
SRC_DIR = src
BUILD_DIR = build
CC_FLAGS = -Wall -m64
CXX_FLAGS = -Wall -m64 -std=c++11
INCL_PATH = -I C:\VulkanSDK\1.2.154.1\Include \
            -I C:\freetype
LIB_PATH = -L build\deng\lib

LIBSURFACE_TARGET = $(BUILD_DIR)\deng\lib\libsurface.a
LIBSURFACE_OBJ = $(BUILD_DIR)\obj\libsurface\key_translation.c.o \
                 $(BUILD_DIR)\obj\libsurface\key_vector.c.o \
                 $(BUILD_DIR)\obj\libsurface\vulkan_handler.c.o \
                 $(BUILD_DIR)\obj\libsurface\win32_surface.c.o

LIBDAS_TARGET = $(BUILD_DIR)\deng\lib\libdas.dll
LIBDAS_OBJ = $(BUILD_DIR)\obj\libdas\das_handler.c.o \
             $(BUILD_DIR)\obj\libdas\data_loader.c.o \
             $(BUILD_DIR)\obj\libdas\common.c.o

LIBCOMMON_TARGET = $(BUILD_DIR)\deng\lib\libcommon.dll
LIBCOMMON_OBJ = $(BUILD_DIR)\obj\libcommon\common.c.o

DAM_TARGET = $(BUILD_DIR)\deng\dam
DAM_OBJ = $(BUILD_DIR)\obj\dam\dam.c.o

DENG_TARGET = $(BUILD_DIR)\deng\deng
DENG_OBJ = $(BUILD_DIR)\obj\deng\sandbox.cpp.o \
           $(BUILD_DIR)\obj\deng\camera.cpp.o \
           $(BUILD_DIR)\obj\deng\rend_helpers.cpp.o \
           $(BUILD_DIR)\obj\deng\renderer.cpp.o \
           $(BUILD_DIR)\obj\deng\window.cpp.o \
           $(BUILD_DIR)\obj\deng\deng_math.cpp.o \
           $(BUILD_DIR)\obj\deng\events.cpp.o \
           $(BUILD_DIR)\obj\deng\font.cpp.o \
           $(BUILD_DIR)\obj\deng\timer.cpp.o

.init:
	.\init.bat $(BUILD_DIR)

.cpy: .init
	Xcopy /E /I objects $(BUILD_DIR)\deng\objects
	Xcopy /E /I src\dengui\css $(BUILD_DIR)\deng\ui_styling
	Xcopy /E /I shaders $(BUILD_DIR)\deng\shaders
	Xcopy /E /I assets $(BUILD_DIR)\deng\assets
	Xcopy /E /I textures $(BUILD_DIR)\deng\textures

all: .cpy $(LIBSURFACE_TARGET) $(LIBDAS_TARGET) $(LIBCOMMON_TARGET) $(DAM_TARGET) $(DENG_TARGET)

$(LIBSURFACE_TARGET): .init $(LIBSURFACE_OBJ)
	ar rs $(LIBSURFACE_TARGET) $(LIBSURFACE_OBJ)
$(BUILD_DIR)\obj\libsurface\key_translation.c.o: $(SRC_DIR)\surface\key_translation.c
	$(CC) -c $(SRC_DIR)\surface\key_translation.c -o $(BUILD_DIR)\obj\libsurface\key_translation.c.o $(CC_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\libsurface\key_vector.c.o: $(SRC_DIR)\surface\key_vector.c
	$(CC) -c $(SRC_DIR)\surface\key_vector.c -o $(BUILD_DIR)\obj\libsurface\key_vector.c.o $(CC_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\libsurface\vulkan_handler.c.o: $(SRC_DIR)\surface\vulkan_handler.c
	$(CC) -c $(SRC_DIR)\surface\vulkan_handler.c -o $(BUILD_DIR)\obj\libsurface\vulkan_handler.c.o $(CC_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\libsurface\win32_surface.c.o: $(SRC_DIR)\surface\win32_surface.c
	$(CC) -c $(SRC_DIR)\surface\win32_surface.c -o $(BUILD_DIR)\obj\libsurface\win32_surface.c.o $(CC_FLAGS) $(INCL_PATH)

$(LIBDAS_TARGET): .init $(LIBDAS_OBJ)
	$(CC) -shared -o $(LIBDAS_TARGET) $(LIBDAS_OBJ) $(CC_FLAGS)
$(BUILD_DIR)\obj\libdas\das_handler.c.o: $(SRC_DIR)\das\das_handler.c
	$(CC) -c $(SRC_DIR)\das\das_handler.c -o $(BUILD_DIR)\obj\libdas\das_handler.c.o -fPIC $(CC_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\libdas\data_loader.c.o: $(SRC_DIR)\das\data_loader.c
	$(CC) -c $(SRC_DIR)\das\data_loader.c -o $(BUILD_DIR)\obj\libdas\data_loader.c.o -fPIC $(CC_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\libdas\common.c.o: $(SRC_DIR)\common\common.c
	$(CC) -c $(SRC_DIR)\common\common.c -o $(BUILD_DIR)\obj\libdas\common.c.o -fPIC $(CC_FLAGS) $(INCL_PATH)

$(LIBCOMMON_TARGET): .init $(LIBCOMMON_OBJ)
	$(CC) -shared -o $(LIBCOMMON_TARGET) $(LIBCOMMON_OBJ) $(CC_FLAGS)
$(BUILD_DIR)\obj\libcommon\common.c.o: $(SRC_DIR)\common\common.c
	$(CC) -c $(SRC_DIR)\common\common.c -o $(BUILD_DIR)\obj\libcommon\common.c.o -fPIC $(CC_FLAGS) $(INCL_PATH)

$(DAM_TARGET): .init $(DAM_OBJ) $(LIBSURFACE_TARGET) $(LIBDAS_TARGET) $(LIBCOMMON_TARGET)
	$(CC) -o $(DAM_TARGET) $(DAM_OBJ) $(CC_FLAGS) $(INCL_PATH) $(LIB_PATH) -ldas -lcommon
$(BUILD_DIR)\obj\dam\dam.c.o: $(SRC_DIR)\das\dam.c
	$(CC) -c $(SRC_DIR)\das\dam.c -o $(BUILD_DIR)\obj\dam\dam.c.o $(CC_FLAGS) $(INCL_PATH)

$(DENG_TARGET): .init $(DENG_OBJ) $(LIBSURFACE_TARGET) $(LIBDAS_TARGET) $(LIBCOMMON_TARGET)
	$(CXX) -o $(DENG_TARGET) $(DENG_OBJ) $(CXX_FLAGS) $(INCL_PATH) $(LIB_PATH) -ldas -lsurface -lcommon -lfreetype -lcomctl32 -lvulkan-1
$(BUILD_DIR)\obj\deng\sandbox.cpp.o: $(SRC_DIR)\main\sandbox.cpp
	$(CXX) -c $(SRC_DIR)\main\sandbox.cpp -o $(BUILD_DIR)\obj\deng\sandbox.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\camera.cpp.o: $(SRC_DIR)\core\camera.cpp
	$(CXX) -c $(SRC_DIR)\core\camera.cpp -o $(BUILD_DIR)\obj\deng\camera.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\rend_helpers.cpp.o: $(SRC_DIR)\core\rend_helpers.cpp
	$(CXX) -c $(SRC_DIR)\core\rend_helpers.cpp -o $(BUILD_DIR)\obj\deng\rend_helpers.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\renderer.cpp.o: $(SRC_DIR)\core\renderer.cpp
	$(CXX) -c $(SRC_DIR)\core\renderer.cpp -o $(BUILD_DIR)\obj\deng\renderer.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\window.cpp.o: $(SRC_DIR)\core\window.cpp
	$(CXX) -c $(SRC_DIR)\core\window.cpp -o $(BUILD_DIR)\obj\deng\window.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\deng_math.cpp.o: $(SRC_DIR)\maths\deng_math.cpp
	$(CXX) -c $(SRC_DIR)\maths\deng_math.cpp -o $(BUILD_DIR)\obj\deng\deng_math.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\events.cpp.o: $(SRC_DIR)\maths\events.cpp
	$(CXX) -c $(SRC_DIR)\maths\events.cpp -o $(BUILD_DIR)\obj\deng\events.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\font.cpp.o: $(SRC_DIR)\utilities\font.cpp
	$(CXX) -c $(SRC_DIR)\utilities\font.cpp -o $(BUILD_DIR)\obj\deng\font.cpp.o $(CXX_FLAGS) $(INCL_PATH)
$(BUILD_DIR)\obj\deng\timer.cpp.o: $(SRC_DIR)\utilities\timer\timer.cpp
	$(CXX) -c $(SRC_DIR)\utilities\timer\timer.cpp -o $(BUILD_DIR)\obj\deng\timer.cpp.o $(CXX_FLAGS) $(INCL_PATH)

.PHONY: clean
clean:
	del /s /q $(BUILD_DIR)\deng\*
	for /d %x in ($(BUILD_DIR)\deng\*) do @rd /s /q %x
	del $(BUILD_DIR)\obj\libsurface\*.o
	del $(BUILD_DIR)\obj\libdas\*.o
	del $(BUILD_DIR)\obj\libcommon\*.o
	del $(BUILD_DIR)\obj\dam\*.o
	del $(BUILD_DIR)\obj\deng\*.o
