/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __VULKAN_RENDERER_H
#define __VULKAN_RENDERER_H

#ifdef __VULKAN_RENDERER_CPP
    #include <vector>
    #include <mutex>
    #include <array>
    
    #include <vulkan/vulkan.h>
    #include <common/base_types.h>
    #include <common/hashmap.h>
    #include <common/uuid.h>
    #include <common/err_def.h>
    #include <data/assets.h>

    #include <math/deng_math.h>
    #include <deng/window.h>
    #include <utils/timer.h>
    #include <deng/camera.h>

    #include <deng/vulkan/vulkan_qm.h>
    #include <deng/vulkan/vulkan_sd.h>
    #include <deng/vulkan/vulkan_resources.h>

    #include <deng/lighting/light_srcs.h>
    #include <deng/registry/registry.h>
    #include <utils/font.h>

    #include <deng/vulkan/vulkan_rend_infos.h>
    #include <deng/vulkan/vulkan_ic.h>
    #include <deng/vulkan/vulkan_scc.h>
    #include <deng/vulkan/vulkan_desc_c.h>
    #include <deng/vulkan/vulkan_dc.h>
    #include <deng/vulkan/vulkan_ra.h>
#endif


namespace deng {
    namespace vulkan {
        /*
         * Contains pointers to Vulkan renderer setup class instances
         */
        struct __vk_RendererInitialisers {
            __vk_InstanceCreator *m_p_ic = NULL;
            __vk_SwapChainCreator *m_p_scc = NULL;
            __vk_DescriptorCreator *m_p_desc_c; 
            __vk_ResourceManager *m_p_rm = NULL;
            __vk_DrawCaller *m_p_dc = NULL;
        };


        /*
         * This class is used for updating frame generation in
         * renderer during runtime.
         * It should be noted that calling any methods from runtime updater
         * assumes that no device queue operations are active
         */
        class __vk_RuntimeUpdater : protected __vk_RendererInitialisers {
        protected:
            std::vector<deng_Id> m_assets;
            std::vector<deng_Id> m_textures;

        protected:

            /*
             * This method updates the vertices buffer that is allocated by
             * given assets
             */
            void __updateAssetVerts(const dengMath::vec2<deng_ui32_t> &asset_bounds);


            /*
             * Rerecord existing commandbuffers 
             */
            void __updateCmdBuffers(const dengMath::vec4<deng_vec_t> &background);
        };


        /*
         * Vulkan renderer config variables
         */
        struct __vk_ConfigVars {
            VkSampleCountFlagBits msaa_sample_count = VK_SAMPLE_COUNT_1_BIT;
            deng_bool_t enable_vsync = false;
            deng_bool_t enable_validation_layers = false;
            deng_bool_t gui_count_fps = false;
            deng_bool_t cli_count_fps = false;
            dengMath::vec4<deng_vec_t> background = {0.0f, 0.0f, 0.0f, 1.0f};
            deng::Camera3D *p_cam;
        };


        /* 
         * Main renderer class for vulkan API
         */
        class __vk_Renderer : private __vk_RuntimeUpdater {
        private:
            __GlobalRegistry &m_reg;
            deng::Window &m_win;
            __vk_ConfigVars m_config;

            // This is reserved for future use
            dengUtils::StringRasterizer *m_p_sr = NULL;

            std::vector<deng_Id> m_assets;
            std::vector<deng_Id> m_textures;

        private:
            /*
             * Create new renderer creator instances
             */
            void __initConstruct();

            /*
             * Free and destroy all active Vulkan API specific instances
             */
            void __cleanup();


            void __cleanRendImgResources();
            void __cleanDrawCommands();
            void __cleanTextures();
            void __cleanAssets();
            void __cleanPipelines();
            void __cleanDSL();
            void __freeBuffers();
            void __cleanSemaphores();
            void __cleanDevice();

            void __makeFrame();

        public:
            __vk_Renderer (
                deng::Window &win,
                const __vk_ConfigVars &cnf,
                deng::__GlobalRegistry &reg
            );


            ~__vk_Renderer();

            /*
             * Add new assets to renderer asset list.
             * No descriptor sets are allocated since that
             * will be done when renderer is being fully initialised.
             */
            void submitAssets (
                deng_Id *asset_ids,
                deng_ui32_t asset_c
            );


            /*
             * Add new textures to renderer texture list.
             */
            void submitTextures (
                deng_Id *tex_ids,
                deng_ui32_t tex_c
            );


            /*
             * Submit new draw call
             */
            void makeFrame();


            /*
             * Setup the renderer, create descriptor sets, allocate buffers
             * and record command buffers
             */
            void setup();


            /*
             * Wait for any queue operation to finish
             * This method needs to be called whenever any 
             * command or data buffers need to be updated
             */
            void idle();
        };
    }
}

#endif
