/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __VULKAN_RENDERER_H
#define __VULKAN_RENDERER_H

#ifdef __VULKAN_RENDERER_CPP
    #include <vector>
    #include <array>
    
    #include <vulkan/vulkan.h>
    #include <common/base_types.h>
    #include <common/hashmap.h>
    #include <common/err_def.h>
    #include <das/assets.h>

    #include <math/deng_math.h>
    #include <deng/surface_window.h>
    #include <deng/window.h>
    #include <deng/vulkan/vulkan_qm.h>
    #include <deng/vulkan/vulkan_sd.h>
    #include <deng/vulkan/vulkan_resources.h>
    #include <deng/vulkan/vulkan_rend_infos.h>
    #include <deng/vulkan/vulkan_ic.h>
    #include <deng/vulkan/vulkan_scc.h>
    #include <deng/vulkan/vulkan_desc_c.h>
    #include <deng/vulkan/vulkan_dc.h>
    #include <deng/vulkan/vulkan_ra.h>

    #include <utils/font.h>
#endif


namespace deng {
    namespace vulkan {
        /*
         * Contains pointers to Vulkan renderer setup class instances
         */
        struct __vk_RendererInitialisers {
            __vk_InstanceCreator *m_p_ic = NULL;
            __vk_SwapChainCreator *m_p_scc = NULL;
            __vk_DescriptorCreator *m_p_desc_c; 
            __vk_ResourceManager *m_p_rm = NULL;
            __vk_DrawCaller *m_p_dc = NULL;
        };


        /*
         * This class is used for updating frame generation in
         * renderer during runtime.
         * It should be noted that calling any methods from runtime updater
         * assumes that no device queue operations are active
         */
        class __vk_RuntimeUpdater : protected __vk_RendererInitialisers {
        private:
            std::vector<__vk_Asset> *m_p_assets;
            std::vector<__vk_Texture> *m_p_textures;
            Hashmap *m_p_asset_map;
            Hashmap *m_p_tex_map;

        protected:
            __vk_RuntimeUpdater(const __vk_AssetsInfo &assets);


            /*
             * This method updates the vertices buffer that is allocated by
             * given assets
             */
            void __updateAssetVerts(const dengMath::vec2<deng_ui32_t> &asset_bounds);


            /*
             * Rerecord existing commandbuffers 
             */
            void __updateCmdBuffers(const dengMath::vec4<deng_vec_t> &background);
             

            /*
             * Free everything from texture buffer and reallocate
             */
            void __realignTextureBuffers();

            
            /*
             * Free all buffers related to asset data and reallocate them
             */
            void __realignAssetBuffers();
        };


        /*
         * Vulkan renderer config variables
         */
        struct __vk_ConfigVars {
            VkSampleCountFlagBits msaa_sample_count = VK_SAMPLE_COUNT_1_BIT;
            deng_bool_t enable_vsync = false;
            deng_bool_t enable_validation_layers = false;
            deng_bool_t gui_count_fps = false;
            deng_bool_t cli_count_fps = false;
            deng_vec_t near_plane;
            deng_vec_t far_plane;
            dengMath::vec4<deng_vec_t> background = {0.0f, 0.0f, 0.0f, 1.0f};


            // This is the currently used camera instance which can be changed
            // in Lua scripts in the future
            void *p_camera = NULL;
            deng_CameraType cam_type;
        };


        /* 
         * Main renderer class for vulkan API
         */
        class __vk_Renderer : private __vk_RuntimeUpdater {
        private:
            __vk_ConfigVars m_config;

            // This is reserved for future
            dengUtils::StringRasterizer *m_p_sr = NULL;

            // Assets and textures
            std::vector<__vk_Asset> m_assets;
            std::vector<__vk_Texture> m_textures;

            Hashmap m_asset_map;
            Hashmap m_tex_map;

            deng::Window *m_p_win;

        private:
            /*
             * Create new renderer creator instances
             */
            void __initConstruct();




            /*
             * Free and destroy all active Vulkan API specific instances
             */
            void __cleanup();


            /*
             * Free asset and texture memory
             */
            void __cleanAssets();
            void __makeFrame();

        public:
            __vk_Renderer (
                deng::Window *p_win,
                const __vk_ConfigVars &cnf
            );


            ~__vk_Renderer();

            /*
             * Add new assets to renderer asset list.
             * PS! UUIDs must be previously generated!
             * Also no descriptor sets are allocated since that
             * will be done when renderer is being fully initialised.
             */
            void submitAssets (
                das_Asset *assets,
                deng_i32_t asset_c
            );


            /*
             * Add new textures to renderer texture list.
             * PS! UUIDs must be previously generated!
             */
            void submitTextures (
                das_Texture *textures,
                deng_i32_t tex_c
            );


            /*
             * This method changes the texture of given asset
             * to the one with given uuid.
             */
            void changeTexture (
                const char *asset_uuid, 
                const char *tex_uuid
            );
            

            /*
             * Submit new draw call
             */
            void makeFrame();


            /*
             * Setup the renderer, create descriptor sets, allocate buffers
             * and record command buffers
             */
            void setup();


            /*
             * Wait for any queue operation to finish
             * This method needs to be called whenever any 
             * command or data buffers need to be updated
             */
            void idle();
        };
    }
}

#endif
