/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef BASE_TYPES_H
#define BASE_TYPES_H
#include <stdint.h>

#define PI 3.14159

/* Main deng integer types */
typedef uint64_t deng_ui64_t;
typedef int64_t deng_i64_t;

typedef uint32_t deng_ui32_t;
typedef int32_t deng_i32_t;

typedef uint16_t deng_ui16_t;
typedef int16_t deng_i16_t;

typedef uint8_t deng_ui8_t;
typedef int8_t deng_i8_t;

typedef float deng_f32_t;
typedef double deng_f64_t;

typedef uint8_t deng_bool_t;

/* Size types */
typedef int64_t deng_px_t;
typedef float deng_vec_t;
#define true 1
#define false 0

typedef deng_ui32_t deng_CameraUniformFlagBits;
#define DENG_CAMERA_UNIFORM_ORTHOGRAPHIC_CAMERA_MODE_3D 0x01u
#define DENG_CAMERA_UNIFORM_PERSPECTIVE_CAMERA_MODE_3D  0x02u
#define DENG_CAMERA_UNIFORM_ORTHOGRAPHIC_CAMERA_MODE_2D 0x04u
#define DENG_CAMERA_UNIFORM_NO_CAMERA_MODE_2D           0x08u
#define DENG_CAMERA_UNIFORM_NO_CAMERA_MODE_3D           0x10u

/* Hints for controlling window with API calls */
typedef deng_ui32_t deng_WindowHintBits;
#define DENG_WINDOW_HINT_FULL_SCREEN                    0x01u
#define DENG_WINDOW_HINT_WINDOWED                       0x02u
#define DENG_WINDOW_HINT_NO_MOUSE_LOCK                  0x04u
#define DENG_WINDOW_HINT_NO_CURSOR_HIDE                 0x08u

/* Hints for controlling renderer features */
typedef deng_ui16_t deng_RendererHintBits;
#define DENG_RENDERER_HINT_API_VULKAN                       0x0001u
#define DENG_RENDERER_HINT_API_OPENGL                       0x0002u
#define DENG_RENDERER_HINT_ENABLE_VSYNC                     0x0004u
#define DENG_RENDERER_HINT_SHOW_CMD_FPS_COUNTER             0x0008u
#define DENG_RENDERER_HINT_SHOW_GUI_FPS_COUNTER             0x0010u
#define DENG_RENDERER_HINT_ENABLE_VALIDATION_LAYERS         0x0020u
#define DENG_RENDERER_HINT_MSAA_MAX_HARDWARE_SUPPORTED      0x0040u
#define DENG_RENDERER_HINT_MSAA_64                          0x0080u
#define DENG_RENDERER_HINT_MSAA_32                          0x0100u
#define DENG_RENDERER_HINT_MSAA_16                          0x0200u
#define DENG_RENDERER_HINT_MSAA_8                           0x0400u
#define DENG_RENDERER_HINT_MSAA_4                           0x0800u
#define DENG_RENDERER_HINT_MSAA_2                           0x1000u
#define DENG_RENDERER_HINT_MSAA_1                           0x2000u
#define DENG_RENDERER_HINT_MIPMAP_ENABLE                    0x4000u
#define DENG_RENDERER_HINT_CUSTOM_LOOP                      0x8000u


/* Coordinate axis specifier */
typedef enum deng_CoordinateAxisType {
    DENG_COORD_AXIS_UNDEFINED = -1,
    DENG_COORD_AXIS_X = 0,
    DENG_COORD_AXIS_Y = 1,
    DENG_COORD_AXIS_Z = 2
} deng_CoordinateAxisType;


/* Movement mode specifier */
typedef enum deng_MovementEvent {
    DENG_MOVEMENT_NONE = -1,
    DENG_MOVEMENT_FORWARD = 0,
    DENG_MOVEMENT_BACKWARD = 1,
    DENG_MOVEMENT_RIGHTWARD = 2,
    DENG_MOVEMENT_LEFTWARD = 3,
    DENG_MOVEMENT_UPWARD = 4,
    DENG_MOVEMENT_DOWNWARD = 5
} deng_MovementEvent;


/* Pipeline type specifier */
typedef enum deng_PipelineType {
    DENG_PIPELINE_TYPE_UNMAPPED_3D = 0,
    DENG_PIPELINE_TYPE_UNMAPPED_3D_NORM = 1,
    DENG_PIPELINE_TYPE_TEXTURE_MAPPED_3D = 2,
    DENG_PIPELINE_TYPE_TEXTURE_MAPPED_3D_NORM = 3,
    DENG_PIPELINE_TYPE_UNMAPPED_2D = 4,
    DENG_PIPELINE_TYPE_TEXTURE_MAPPED_2D = 5
} deng_PipelineType;


/* Triangle angle specifier */
typedef enum deng_TriangleAngleType {
    DENG_TRIANGLE_ANGLE_ALPHA = 0,
    DENG_TRIANGLE_ANGLE_BETA = 1,
    DENG_TRIANGLE_ANGLE_GAMMA = 2
} deng_TriangleAngleType;


/* Renderer usage mode */
typedef enum deng_RendererUsageMode {
    DENG_RENDERER_USAGE_ASSET_EDITOR = 0,
    DENG_RENDERER_USAGE_MAP_EDITOR = 1,
    DENG_RENDERER_USAGE_GAME_MODE = 2,
} deng_RendererUsageMode;


/* Camera type specifier */
typedef enum deng_CameraType {
    DENG_CAMERA_FPP     = 0,
    DENG_CAMERA_EDITOR  = 1
} deng_CameraType;


/* Editor camera event specifier */
typedef enum deng_EditorCameraEvent {
    DENG_EDITOR_CAMERA_NONE         = -1,
    DENG_EDITOR_CAMERA_Z_MOV_IN     = 0,
    DENG_EDITOR_CAMERA_Z_MOV_OUT    = 1,
    DENG_EDITOR_CAMERA_MOUSE_ROTATE = 2
} deng_EditorCameraEvent;


/* 
 * Specify input device type for action lookup
 */
typedef enum deng_InputType {
    DENG_INPUT_TYPE_MOUSE   = 0,
    DENG_INPUT_TYPE_KB      = 1
} deng_InputType;


/*
 * Specify input event type for lookup
 */
typedef enum deng_InputEventType {
    DENG_INPUT_EVENT_TYPE_ACTIVE    = 0,
    DENG_INPUT_EVENT_TYPE_RELEASED  = 1
} deng_InputEventType;


/*
 * Specify what should happen if virtual cursor achives 
 * its maximum or minimum position 
 */
typedef enum deng_VCPOverflowAction {
    DENG_VCP_OVERFLOW_ACTION_TO_OPPOSITE_POSITION   = 0,
    DENG_VCP_OVERFLOW_ACTION_BLOCK_POSITION         = 1,
    DENG_VCP_OVERFLOW_ACTION_NONE                   = 2
} deng_VCPOverflowAction;


#define DENG_KEY_PRESS_INTERVAL         500 // ms
#define DENG_MOVEMENT_INTERVAL          17 // ms

#define DENG_CAMERA_BASE_SPEED_X        0.015
#define DENG_CAMERA_BASE_SPEED_Y        0.015
#define DENG_CAMERA_BASE_SPEED_Z        -0.015

#define DENG_FPP_CAMERA_DEFAULT_POS_X   0.0f
#define DENG_FPP_CAMERA_DEFAULT_POS_Y   0.5f
#define DENG_FPP_CAMERA_DEFAULT_POS_Z   0.5f

// World coordinates
#define DENG_EDITOR_CAMERA_DEFAULT_POS_X    0.0f
#define DENG_EDITOR_CAMERA_DEFAULT_POS_Y    0.0f
#define DENG_EDITOR_CAMERA_DEFAULT_POS_Z    3.0f
#define DENG_EDITOR_CAMERA_DEFAULT_X_ROT    dengMath::Conversion::degToRad(-30.0f)
#define DENG_EDITOR_CAMERA_DEFAULT_Y_ROT    dengMath::Conversion::degToRad(30.0f)
#endif
