/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __UUID_H
#define __UUID_H

#ifdef __cplusplus
extern "C" {
#endif

    #ifdef __UUID_C
        #include <stdlib.h>
        #include <stdint.h>
        #include <stdio.h>
        #include <time.h>
        #include <string.h>
        #include <limits.h>

        #ifdef __linux__
            #include <dirent.h>
            #include <linux/random.h>
        #endif


        #include <common/base_types.h>
        #include <common/cerr_def.h>
        
        #define __UUID_VERSION 0x10
        #define __UUID_VARIANT 0x40
        #define __UUID_VARIANT_C    2
        #define __LINUX_NET_DEV_DIR     "/sys/class/net"
        
        /*
         * Basic structure for 16 byte UUID storage byte per byte
         */
        typedef struct UUIDType {
            deng_ui8_t bytes[10];
        } UUIDType;

        UUIDType __uuid = {0};
        deng_ui8_t __clock_seq[2];


        /*
         * Find first non lo network device's mac address
         */
        char *__uuid_GetDevMacAddress();
    #endif

    /*
     * Init new uuid instance
     */
    char *uuid_Generate();


#ifdef __cplusplus
}
#endif
#endif
