/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __SANDBOX_CPP
#include <../src/main/vulkan/vulkan_sandbox.h>

extern deng::__SharedMouseData __ext_md;

namespace Sandbox {

    VulkanApp::VulkanApp() : 
        m_win(1200, 1000, "DENG game"),
        m_cam (
            DENG_CAMERA_TYPE_FPP,
            static_cast<deng_vec_t>(dengMath::Conversion::degToRad(65.0)),
            {0.1f, -25.0f},
            {0.7f, 0.7f, 0.7f},
            {0.3f, 0.3f},
            false,
            &m_win
    ) {
        // Setup code that will be done in Lua when the scripting layer is added
        switch(m_cam.getType())
        {
        case DENG_CAMERA_TYPE_EDITOR:
            __bindEditor();
            break;

        case DENG_CAMERA_TYPE_FPP:
            __bindFPP();
            break;

        default:
            break;
        }

        m_tex_uuids.reserve(4);
        __loadTextures ({
            "textures/brick.tga",
            "textures/viking_room.tga",
            "textures/statue.tga"
        });

        m_asset_uuids.reserve(4);
        __loadAssets ({
            "assets/viking.das"
        });

        deng::vulkan::__vk_ConfigVars cfg;
        cfg.background = dengMath::vec4<deng_vec_t>{ 0.f, 0.f, 0.f, 1.f };
        cfg.enable_validation_layers = true;
        cfg.enable_vsync = true;
        cfg.p_cam = &m_cam;
        cfg.msaa_sample_count = VK_SAMPLE_COUNT_4_BIT;

        m_p_rend = new deng::vulkan::__vk_Renderer (
            m_win, 
            cfg, 
            m_reg
        );

        deng::RegType *p_reg_asset;
        p_reg_asset = m_reg.retrievePtr(m_asset_uuids[0], DENG_SUPPORTED_REG_TYPE_ASSET);
        p_reg_asset->asset.tex_uuid = m_tex_uuids[1];

        m_p_rend->submitTextures (
            m_tex_uuids.data(), 
            static_cast<deng_ui32_t>(m_tex_uuids.size())
        );

        m_p_rend->submitAssets (
            m_asset_uuids.data(), 
            static_cast<deng_ui32_t>(m_asset_uuids.size())
        );
    }

    
    VulkanApp::~VulkanApp() {
        delete m_p_rend;
    }


    /*
     * Create first person camera control bindings
     */
    void VulkanApp::__bindFPP() {
        deng::Camera3DBindings bindings;
        bindings.mov_u = deng_CreateInputMask(1, DENG_KEY_D);
        bindings.mov_nu = deng_CreateInputMask(1, DENG_KEY_A);
        bindings.mov_v = deng_CreateInputMask(1, DENG_KEY_SPACE);
        bindings.mov_nv = deng_CreateInputMask(1, DENG_KEY_LEFT_CTRL);
        bindings.mov_w = deng_CreateInputMask(1, DENG_KEY_S);
        bindings.mov_nw = deng_CreateInputMask(1, DENG_KEY_W);

        bindings.rot_u = deng_CreateInputMask(1, DENG_MOUSE_DELTA_NY);
        bindings.rot_nu = deng_CreateInputMask(1, DENG_MOUSE_DELTA_Y);
        bindings.rot_v = deng_CreateInputMask(1, DENG_MOUSE_DELTA_NX);
        bindings.rot_nv = deng_CreateInputMask(1, DENG_MOUSE_DELTA_X);
        bindings.ch_vcp = deng_CreateInputMask(1, DENG_KEY_ESCAPE);

        m_cam.setBindings(bindings);
    }


    /*
     * Create editor camera control bindings
     */
    void VulkanApp::__bindEditor() {
        deng::Camera3DBindings bindings;
        bindings.mov_w = deng_CreateInputMask(1, DENG_MOUSE_SCROLL_UP);
        bindings.mov_nw = deng_CreateInputMask(1, DENG_MOUSE_SCROLL_DOWN);
        bindings.ch_vcp = deng_CreateInputMask(1, DENG_MOUSE_BTN_2);

        m_cam.setBindings(bindings);
    }


    /*
     * Load test assets into the register
     */
    void VulkanApp::__loadAssets(const std::vector<const char*> &files) {
        for(size_t i = 0; i < files.size(); i++) {
            deng::RegType reg_elem = {{0}};
            das_LoadAsset (
                &reg_elem.asset,
                DAS_ASSET_MODE_UNDEFINED,
                {0.0f, 0.0f, 1.0f},
                false,
                NULL,
                (char*) files[i]
            );

            m_reg.push (
                reg_elem.asset.uuid, 
                DENG_SUPPORTED_REG_TYPE_ASSET, 
                reg_elem
            );

            m_asset_uuids.push_back(reg_elem.asset.uuid);
        }
    }

    
    /*
     * Load test textures into the register 
     */
    void VulkanApp::__loadTextures(const std::vector<const char*> &files) {
        for(size_t i = 0; i < files.size(); i++) {
            deng::RegType reg_elem = {{0}};
            das_LoadTexture (
                &reg_elem.tex, 
                files[i]
            );

            m_reg.push (
                reg_elem.tex.uuid,
                DENG_SUPPORTED_REG_TYPE_TEXTURE,
                reg_elem
            );

            m_tex_uuids.push_back(reg_elem.tex.uuid);
        }
    }


    void VulkanApp::setup() {
        m_p_rend->setup();
    }


    void VulkanApp::run() {
        while(deng_IsRunning()) {
            __ext_md.mut.lock();
            m_win.update();
            __ext_md.mut.unlock();
            m_cam.update(),
            m_p_rend->makeFrame();
            std::this_thread::sleep_for(std::chrono::microseconds(50));
        }

        m_p_rend->idle();
    }
}

int main(void) {
    Sandbox::VulkanApp vk_app;
    vk_app.setup();
    vk_app.run();
    return 0;
}
