/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __DAM_H
#define __DAM_H


/*
 * DAM has different version than DENG
 */
#define DAM_VERSION "0.1.0"

#ifdef __DAM_C
    #define __DAM_PREVIEW_TITLE     "DAM"
    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    
    #include <common/cerr_def.h>
    #include <common/base_types.h>
    #include <common/common.h>

    #include <das/assets.h>
    #include <das/das_loader.h>
    #include <das/wavefront_obj.h>
#endif


/*
 * Structure for storing asset assembly info 
 */
typedef struct dam_AssetAsmInfo {
    char *model_file;
    char *out_file;
    das_AssetMode am;
} dam_AssetAsmInfo;


/*
 * Structure for specifying asset preview 
 * information
 */
typedef struct dam_AssetPreviewInfo {
    char *file_name;
    das_Asset asset;
    deng_ui32_t width;
    deng_ui32_t height;
    deng_bool_t disable_menus;
} dam_AssetPreviewInfo;


#ifdef __DAM_C
    #define __DAM_DEFAULT_PREVIEW_WIDTH     1280
    #define __DAM_DEFAULT_PREVIEW_HEIGHT    720
    #define __DAM_DEFAULT_ASSET_COLOR       {0.7f, 0.7f, 0.7f, 1.0f}
    const char *__help_text = 
        "Usage flags for DAM:\n" \
        "[ASSET] -- display information about the asset\n" \
        "--version -- view the current version\n" \
        "-h / --help -- view help text\n" \
        "-p / --preview [ASSET] -- create preview for 3D asset\n" \
        "   -g / --geometry [WIDTH]x[HEIGHT] -- specify the preview window size\n" \
        "   --disable-menus -- disable all menus in previews\n" \
        "-n / --new -- create new asset\n" \
        "   -m / --model [FILE NAME] -- path to the model file used\n" \
        "   -o [OUTPUT] -- path to the output file name\n" \
        "   -v / --vert [v, vn, vm, vmn] -- specify the stored vertices\n";


    /*
     * Read information about the asset
     * Information is following:
     *  - Name of the asset
     *  - Date and time of the creation
     *  - Type of vertices
     *  - Total count of unique vertices
     *  - Total count of drawn vertices
     */
    void __dam_ListAsset(char *asset_file);


    /*
     * Find information about asset creation
     */
    dam_AssetAsmInfo __dam_FindAssetAsmInfo(int argc, char *argv[]);


    /*
     * Assemble deng asset from specified asset 
     * assembly flags
     */
    void __dam_AssetAssemblyCaller(dam_AssetAsmInfo asm_info);


    
    /*
     * Find information about asset preview 
     */
    dam_AssetPreviewInfo __dam_FindPreviewInfo(int argc, char *argv[]);


    /*
     * Create new DENG renderer instance and preview
     * given DENG asset file
     */
    void __dam_PreviewAsset(dam_AssetPreviewInfo preview_info);
#endif

#endif

