/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */


#define __GL_BUFFERS_CPP
#include <deng/opengl/buffers.h>


namespace deng {
    namespace opengl {

        __gl_BufferManager::__gl_BufferManager(std::vector<deng_Id> &assets, std::shared_ptr<__gl_ShaderLoader> shader_loader, __GlobalRegistry &reg) :
            __OffsetFinder(assets, reg), m_assets(assets), m_reg(reg), m_shader_loader(shader_loader)
        {
            // Generate new buffers for vertices, indices and uniform data
            glGenBuffers(1, &m_vert_buffer);
            glGenBuffers(1, &m_index_buffer);
            glGenBuffers(1, &m_ubo_buffer);

            // Bind all buffers accordingly
            glBindBuffer(GL_ARRAY_BUFFER, m_vert_buffer);
            glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_index_buffer);
            glBindBuffer(GL_UNIFORM_BUFFER, m_ubo_buffer);

            /// Allocate the initial amount of memory for buffers
            allocateBufferMemory();

            /// Initialise uniform buffer for storing asset data
            initUniformBuffer();
        }


        /// Allocate ui_cap + asset_cap amount of memory for the buffer
        void __gl_BufferManager::allocateBufferMemory() {
            // Allocate memory for vertex buffer
            glBufferData(GL_ARRAY_BUFFER, __OffsetFinder::getSectionInfo().asset_cap + 
                __OffsetFinder::getSectionInfo().ui_cap, NULL, GL_DYNAMIC_DRAW);

            // Allocate memory for indices buffer
            glBufferData(GL_ELEMENT_ARRAY_BUFFER, __OffsetFinder::getSectionInfo().indices_cap, 
                NULL, GL_DYNAMIC_DRAW);
        }


        void __gl_BufferManager::initUniformBuffer() {
            m_shader_loader->getShaderProgram(UM2D_I);          
        }
    }
}
