/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __DAS_FILE_H
#define __DAS_FILE_H

#define __DAS_INFO_HEADER_NAME          "INFO_HDR"
#define __DAS_INFO_HEADER_SIZE          62
#define __DAS_VERTICES_HEADER_NAME      "VERT_HDR"
#define __DAS_INDICES_HEADER_NAME       "INDX_HDR"
#define __DAS_META_HEADER_NAME          "META_HDR"
#define __DAS_STATIC_MAGIC_NUMBER       0x5453544553534144
#define __DAS_ANIMATION_MAGIC_NUMBER    0x4e41544553534144
#define __DAS_MAP_MAGIC_NUMBER          0x504d544553534144
#define __DAS_UUID_LEN                  32

/*
 * Information struct for META_HDR
 */
typedef struct das_META_HDR {
    char beg[8]; // always has to be BEG_HDR
    deng_ui32_t hdr_size;
    deng_ui32_t data_size;
    char *data;
} das_META_HDR;

/*
 * Information structure for INFO_HDR
 */
typedef struct das_INFO_HDR {
    deng_ui64_t magic_number;
    char hdr_name[8];
    deng_ui32_t hdr_size;
    char uuid[__DAS_UUID_LEN];
    deng_ui64_t time_st;
    deng_ui8_t asset_type;
    deng_ui8_t cmpr;
} das_INFO_HDR;


/* 
 * Information structure for VERT_HDR
 */
typedef struct das_VERT_HDR {
    char hdr_name[8];
    deng_ui32_t hdr_size;
    deng_ui32_t vert_c;
} das_VERT_HDR;



/*
 * Information structure for INDX_HDR
 */
typedef struct das_INDX_HDR {
    char hdr_name[8];
    deng_ui32_t hdr_size;
    deng_ui32_t ind_c;
} das_INDX_HDR;

#endif
