/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 * ----------------------------------------------------------------
 *  Name: gl_ubm - OpenGL uniform buffer manager class
 *  Purpose: Provide a class interface for creating and writing to uniform buffers
 *  Author: Karl-Mihkel Ott
 */ 

#ifndef __GL_UBM_H
#define __GL_UBM_H


#ifdef __GL_UBM_CPP
    #include <vector>
    #include <array>
    #include <chrono>
    #include <vulkan/vulkan.h>
    #include <glad/glad.h>

    #include <common/base_types.h>
    #include <common/hashmap.h>
    #include <data/assets.h>
    #include <math/deng_math.h>
    #include <imgui-layer/imgui_entity.h>

    #include <deng/lighting/light_srcs.h>
    #include <deng/registry/registry.h>
    #include <deng/window.h>
    #include <deng/opengl/resources.h>
    #include <deng/cross_api/cross_api.h>
    #include <deng/camera.h>
#endif


namespace deng {
    namespace opengl {


        class __gl_UniformManager : protected __OffsetFinder {
        private:
            __GlobalRegistry &m_reg;
            __gl_Resources &m_resources;

        protected:
            /// Reserve a uniform data memory location for OpenGL asset
            void mapUniformBufferArea(das_Asset &asset);


        public:
            __gl_UniformManager(__GlobalRegistry &reg, std::vector<deng_Id> &assets, __gl_Resources &res);
            

            /// Update uniform transformation data for the frame according to 
            /// camera's view and projection matrix
            void updateUboTransform3D(Camera3D *p_cam);

            
            /// Update asset uniform buffer data
            void updateAssetUboData(das_Asset &asset);

            
            /// Update lighting uniform data
            void updateUboLighting(std::array<deng_Id, __DENG_MAX_LIGHT_SRC_COUNT> &light_srcs);
        };
    }
}

#endif
