/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#ifndef __FPP_CAM_H
#define __FPP_CAM_H


#ifdef __FPP_CAM_CPP
    #include <stdlib.h>
    #include <mutex>
    #include <vulkan/vulkan.h>

    #include <common/base_types.h>
    #include <common/err_def.h>
    #include <das/assets.h>

    #include <math/vec2.h>
    #include <math/vec3.h>
    #include <math/vec4.h>
    #include <math/mat3.h>
    #include <math/mat4.h>
    #include <math/projection_mat.h>
    #include <math/camera_mat.h>
    #include <deng/window.h>
    #include <deng/camera/cam_base.h>
    #include <utils/timer.h>
#endif


namespace deng {
    /*
     * FPPCamera forward declaration
     */
    class __FPPCamera;


    /* 
     * Perspective first person camera event class
     */
    class __FPPCameraEv : protected __EventBase 
    {
    private:
        dengUtils::Timer m_mov_timer;
        dengUtils::Timer m_input_mode_timer;
        dengMath::vec4<deng_vec_t> m_move_speed;
        dengMath::vec3<deng_MovementEvent> m_movements;

    private:
        void __findMovements();
        void __checkForInputModeChange(dengMath::CameraMatrix *p_cm);
        void __update(__FPPCamera *p_cam);
        deng_bool_t __keyEvHandler(deng_Key key);

    public:
        __FPPCameraEv (
            Window *p_win,
            const dengMath::vec2<deng_f64_t> &mouse_sens,
            const dengMath::vec3<deng_vec_t> &camera_mov_speed
        );


        /*
         * Find the correct movement speed
         * Parameters for this method are boolean flags about the axis being opposite or not
         */
        dengMath::vec4<deng_vec_t> getMoveSpeed (
            deng_bool_t op_x,
            deng_bool_t op_y,
            deng_bool_t op_z
        );


        /*
         * Check for input mode changes and move camera if needed
         */
        void updateEv(__FPPCamera *p_cam, deng_bool_t ignore_pitch);


        /*
         * Set the first person perspective camera bindings
         */
        void setBindings(const Camera3DBindings &bindings);

        
        /*
         * Get the pointer to the window instance
         */
        Window *getWinPtr();

        
        /*
         * Set the window pointer
         */
        void setWinPtr(Window *p_win);
    };

        
    /* 
     * First person perspective camera class 
     */
    class __FPPCamera : private __FPPCameraEv, public __CameraBase 
    {
    private:
        deng_bool_t m_is_pitch_ignore;

    public:
        __FPPCamera (
            const dengMath::vec3<deng_vec_t> &camera_mov_speed_mul, 
            const dengMath::vec2<deng_f64_t> &mouse_sens, 
            deng_vec_t fov, 
            deng_vec_t near_plane, 
            deng_vec_t far_plane, 
            deng_bool_t ignore_pitch_mov,
            Window *p_win
        );


        /* 
         * FPPCamera wrapper method for event update 
         */
        void update(); 

        
        /*
         * Set first person camera control bindings
         */
        void setBindings(const Camera3DBindings &bindings);

        
        /*
         * Check if camera movement system should ignore pitch rotation, when translating
         * movements into camera coordinate system.
         */
        deng_bool_t isPitchIgnore();

        
        /*
         * Get the pointer to camera matrix instance
         */
        dengMath::CameraMatrix *getCamMatPtr();
    };


}

#endif
