/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" m_texturest file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE m_texturest file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE m_texturest from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __REND_INIT_CPP
#include <deng/vulkan/rend_init.h>


namespace deng {
    namespace vulkan {

        /// External frame count variable declaration
        extern deng_ui32_t __max_frame_c;

        
        __vk_RendererInitialiser::__vk_RendererInitialiser (
            deng::Window &win, 
            const __vk_ConfigVars &conf,
            deng::__GlobalRegistry &reg,
            std::vector<deng_Id> &assets,
            std::vector<deng_Id> &textures
        ) : m_reg(reg), m_assets(assets), m_textures(textures) {

            // Create new VkInstace
            m_p_ic = new __vk_InstanceCreator(win, conf.enable_validation_layers);
            
            // Create new swapchain creator
            m_p_scc = new __vk_SwapChainCreator(m_p_ic->getDev(),
                win, m_p_ic->getGpu(), m_p_ic->getSu(), m_p_ic->getQFF(),
                conf.msaa_sample_count);

            // Create new draw caller instance and make command pool
            m_p_dc = new __vk_DrawCaller(m_p_ic->getDev(),
                m_p_ic->getQFF(), m_assets, m_textures, m_reg);
            
            m_p_dc->mkCommandPool(m_p_ic->getDev());

            __max_frame_c = static_cast<deng_ui32_t>(m_p_scc->getSCImg().size());

            // Create new buffer resources allocator
            m_p_rm = new __vk_ResourceManager(m_p_ic->getDev(), 
                m_p_ic->getGpu(), m_p_scc->getExt(), conf.msaa_sample_count,
                m_p_scc->getRp(), m_p_dc->getComPool(), m_p_ic->getQFF().graphics_queue,
                m_p_scc->getSCImgViews(), m_reg, m_assets, m_textures, m_p_scc->getSF(),
                m_p_ic->getGpuLimits()); 

            // Create new vulkan descriptor creator
            m_p_desc_c = new __vk_DescriptorSetsCreator(m_p_ic->getDev(),
                m_p_scc->getExt(), m_p_scc->getRp(), m_reg, m_assets,
                m_textures, conf.msaa_sample_count);

            // Create new vulkan pipeline creator
            m_p_pl_c = new __vk_PipelineCreator (
                m_p_desc_c->getLayout(DAS_ASSET_MODE_2D_UNMAPPED),
                m_p_desc_c->getLayout(DAS_ASSET_MODE_2D_TEXTURE_MAPPED),
                m_p_desc_c->getLayout(DAS_ASSET_MODE_3D_UNMAPPED),
                m_p_desc_c->getLayout(DAS_ASSET_MODE_3D_TEXTURE_MAPPED)
            );
        }


        __vk_RendererInitialiser::~__vk_RendererInitialiser() {
            delete m_p_desc_c;
            delete m_p_pl_c;
            delete m_p_dc;
            delete m_p_rm;
            delete m_p_scc;
            delete m_p_ic;
        }


        /// Renderer initialiser getter methods
        __vk_InstanceCreator &__vk_RendererInitialiser::getIC() { return *m_p_ic; }
        __vk_SwapChainCreator &__vk_RendererInitialiser::getSCC() { return *m_p_scc; } 
        __vk_DescriptorSetsCreator &__vk_RendererInitialiser::getDescC() { return *m_p_desc_c; }
        __vk_PipelineCreator &__vk_RendererInitialiser::getPipelineC() { return *m_p_pl_c; }
        __vk_ResourceManager &__vk_RendererInitialiser::getResMan() { return *m_p_rm; }
        __vk_DrawCaller &__vk_RendererInitialiser::getDrawCaller() { return *m_p_dc; }
    }
}
