/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 * ----------------------------------------------------------------
 *  Name: runtime_updater - Runtime buffer data updater
 *  Purpose: Provide a class interface for manipulating data during runtime
 *  Author: Karl-Mihkel Ott
 */ 


#define __RUNTIME_UPDATE_CPP
#include <deng/vulkan/runtime_updater.h>


namespace deng {
    namespace vulkan {


        __vk_RuntimeUpdater::__vk_RuntimeUpdater (
            __vk_InstanceCreator *p_ic,
            __vk_SwapChainCreator *p_scc,
            __vk_DrawCaller *p_dc,
            __vk_ResourceManager *p_rm,
            std::vector<deng_Id> &assets, 
            std::vector<deng_Id> &tex
        ) : m_ref_assets(assets), m_ref_tex(tex) {
            m_p_ic = p_ic;
            m_p_scc = p_scc;
            m_p_dc = p_dc;
            m_p_rm = p_rm;
        }


        /*
         * This method updates the vertices buffer that is allocated by
         * given assets
         */
        void __vk_RuntimeUpdater::__updateAssetVerts(const dengMath::vec2<deng_ui32_t> &asset_bounds) {
            m_p_rm->remapAssetVerts (
                m_p_ic->getDev(),
                m_p_ic->getGpu(),
                m_p_dc->getComPool(),
                m_p_ic->getQFF().graphics_queue,
                asset_bounds
            );
        }

        
        /*
         * Free and reallocate new commandbuffers 
         */
        void __vk_RuntimeUpdater::__updateCmdBuffers(const dengMath::vec4<deng_vec_t> &background) {
            m_p_dc->recordMainCmdBuffers (
                m_p_scc->getRp(),
                m_p_scc->getExt(),
                background,
                m_p_rm->getBD()
            );
        }

    }
}
