/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __PROJECTION_MAT_CPP
#include <math/projection_mat.h>


namespace dengMath {

    ProjectionMatrix::ProjectionMatrix (
        deng_vec_t fov,
        const vec2<deng_vec_t> &planes,
        deng_vec_t aspect_ratio
    ) {
        m_fov = fov;
        m_near = planes.first;
        m_far = planes.second;
        m_aspect_ratio = aspect_ratio;

        __calcMatrix();
    }


    /*
     * Calculate the value of the perspective projection matrix
     * from given private class members
     */
    void ProjectionMatrix::__calcMatrix() {
        m_mat.row1 = vec4<deng_vec_t>{m_aspect_ratio / tanf(m_fov / 2), 0.0f, 0.0f, 0.0f};
        m_mat.row2 = vec4<deng_vec_t>{0.0f, 1 / tanf(m_fov / 2), 0.0f, 0.0f};
        m_mat.row3 = vec4<deng_vec_t>{0.0f, 0.0f, m_far / (m_far - m_near), 1.0};
        m_mat.row4 = vec4<deng_vec_t>{0.0f, 0.0f, -(m_far * m_near) / (m_far - m_near), 0.0f};
    }


    /*
     * Change field of view of the matrix
     */
    void ProjectionMatrix::setFov(deng_vec_t fov) {
        m_fov = fov;
        __calcMatrix();
    }


    /*
     * Change surfaces aspect ratio when surface was resized
     */
    void ProjectionMatrix::setAspectRatio(deng_vec_t aspect_ratio) {
        m_aspect_ratio = aspect_ratio;
        __calcMatrix();
    }


    /*
     * Change view near and far view planes
     */
    void ProjectionMatrix::setViewPlanes(const vec2<deng_vec_t> &planes) {
        m_near = planes.first;
        m_far = planes.second;
        __calcMatrix();
    }

    /*
     * Get the calculated projection matrix
     */
    const mat4<deng_vec_t> &ProjectionMatrix::getProjectionMatrix() {
        return m_mat;
    }
}
