/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 * ----------------------------------------------------------------
 *  Name: gpu_mem - gpu memory handling structures and default values
 *  Purpose: Provide some cross api memory handling structures and default values
 *  Author: Karl-Mihkel Ott
 */


#ifndef __GPU_MEMPROPS_H
#define __GPU_MEMPROPS_H

#define DENG_DEF_ASSET_CAP      65536   // Initialise with 64KB of memory for assets
#define DENG_DEF_UI_CAP         32768   // Initialise with 32KB of memory for ui elements


#define DENG_DEF_TEX_WIDTH      512
#define DENG_DEF_TEX_HEIGHT     512
#define DENG_DEF_TEX_SIZE       1048576 // bytes
#define DENG_DEF_TEX_MEM_CAP    8388608 // bytes

namespace deng {

    struct BufferSectionInfo {
        BufferSectionInfo() {
            asset_cap = DENG_DEF_ASSET_CAP;
            asset_size = 0;

            indices_cap = DENG_DEF_ASSET_CAP;
            indices_size = 0;
            
            img_cap = 0;
            img_size = 0;

            ui_cap = DENG_DEF_UI_CAP;
            ui_size = 0;

            ubo_cap = 0;
            ubo_non_asset_size = 0;
            ubo_asset_size = 0;
            ubo_asset_cap = 0;
        }

        // Asset size information
        deng_ui64_t asset_cap;
        deng_ui64_t asset_size;

        // Indices size information
        deng_ui64_t indices_cap;
        deng_ui64_t indices_size;

        // Image data size information
        deng_ui64_t img_cap;
        deng_ui64_t img_size;

        // UI data size information
        deng_ui64_t ui_cap;
        deng_ui64_t ui_size;

        // Uniform buffer data size information
        // NOTE: Data alignment
        // Data in uniform buffers is aligned as follows:
        //  * Uniform data for different pipelines
        //      Data is stored as follows:
        //          - 3D uniform object transformation
        //          - 2D object transformation
        //          - Light source data
        //  * Asset data: 
        //      Each asset contains various coloring information about that certain asset
        //      NOTE: Asset color data structure is different for 3D and 2D assets
        deng_ui64_t ubo_cap;
        deng_ui64_t ubo_non_asset_size;
        deng_ui64_t ubo_asset_size;
        deng_ui64_t ubo_asset_cap;
    };
}

#endif
