/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 * ----------------------------------------------------------------
 *  Name: ed_cam_ev - world editor camera event system
 *  Purpose: Provide a base class for handling 3D world editor camera events
 *  Author: Karl-Mihkel Ott
 */ 


#ifndef __ED_CAM_EV_H
#define __ED_CAM_EV_H


#ifdef __ED_CAM_EV_CPP
    #include <vulkan/vulkan.h>
    #include <common/base_types.h>
    #include <data/assets.h>
    
    #include <math/deng_math.h>
    #include <deng/window.h>
    #include <deng/camera/3d/cam_bindings.h>
    #include <deng/camera/3d/ev_base.h>
#endif


namespace deng {
    
    /// Event handler class for editor camera
    class __EditorCameraEv : protected __Event3DBase {
    private:
        deng_EditorCameraEvent m_editor_cam_ev;
        dengMath::vec2<deng_f64_t> m_last_rot = {0, 0};
        deng_vec_t m_zoom_step;
        deng_bool_t m_is_rot_cur = false;

    protected:
        /// Set the default camera rotation and position values
        void __initCamera(dengMath::CameraMatrix *p_vm, const dengMath::vec4<deng_vec_t> &origin);

        
        /// Check if any camera events have occured
        void __findEditorEvent();


        /// Zoom in the editor camera 
        void __zoomIn(dengMath::CameraMatrix *p_vm);


        /// Zoom out the editor camera
        void __zoomOut(dengMath::CameraMatrix *p_vm);


    public:
        __EditorCameraEv(const dengMath::vec2<deng_f64_t> &mouse_sens, deng_vec_t zoom_step,
            const dengMath::vec3<deng_vec_t> &origin, Window *p_ww);
        

        /// Check new editor camera events from IO bindings and perform camera updates
        void updateEv(dengMath::vec3<deng_vec_t> origin, dengMath::CameraMatrix *p_vm);


        /// Set the editor camera bindings
        void setBindings(const Camera3DBindings &bindings);

        
        /// Get the pointer to the window instance
        Window *getWinPtr();

        
        /// Set the window pointer
        void setWinPtr(Window *p_win);
    };
}

#endif
