/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 * ----------------------------------------------------------------
 *  Name: ev_base - 3D camera event base class
 *  Purpose: Provide a base class for handling 3D camera events
 *  Author: Karl-Mihkel Ott
 */ 


#ifdef __EV_BASE_CPP
    #include <vulkan/vulkan.h>
    #include <common/base_types.h>

    #include <data/assets.h>
    #include <math/deng_math.h>
    #include <deng/window.h>
    
    #include <deng/camera/3d/cam_bindings.h>
#endif


#ifndef __EV_BASE_H
#define __EV_BASE_H


#define BASE_MAX_VC_X   720
#define BASE_MAX_VC_Y   180


namespace deng {

    class __Event3DBase {
    protected:
        Window *m_p_win = NULL;
        dengMath::vec2<deng_px_t> m_mouse_pos = dengMath::vec2<deng_px_t>{0, 0};
        dengMath::vec2<deng_VCPOverflowAction> m_vcp_overflow;
        dengMath::vec2<dengMath::vec2<deng_px_t>> m_vc_bounds;
        dengMath::vec2<deng_f64_t> m_max_rot;
        Camera3DBindings m_bindings;

    protected:

        /// Camera mouse position update method 
        void __updateCameraMousePos();


        /// Find the current mouse control rotation 
        dengMath::vec2<deng_f64_t> __getMouseRotation();


        /// Check if input input conditions are satified for certain action
        deng_bool_t __checkInputAction(deng_CameraAction action);

    public:
        __Event3DBase (
            const dengMath::vec2<deng_VCPOverflowAction> &vcp_act,
            const dengMath::vec2<dengMath::vec2<deng_px_t>> &vc_bounds,
            const dengMath::vec2<deng_f64_t> &max_rot,
            Window *p_win
        );
    };
}

#endif
