#    ____         ________     __      _        ______  
#   |  _ \_      |  ______|   |  \    | |     _/  ____\
#   | | \_ \_    |  |         |   \   | |    /  _/   
#   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
#   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
#   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
#   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
#   |____/       |________|   |_|    \__|       \____/
#               
# __________________________________________________________
# __________________________________________________________
#                       Project DENG 
#
#
# Copyright (C) 2020 - 2021
# This Software is licensed under Apache License as described 
# in the LICENSE.md file, which you should have recieved with 
# this distribution.
# 
# You may reproduce and distribute copies of the
# Work or Derivative Works thereof in any medium, with or without
# modifications, and in Source or Object form, provided that You
# meet the following conditions:
#
# (a) You must give any other recipients of the Work or
#     Derivative Works a copy of this License and
#
# (b) You must cause any modified files to carry prominent notices
#     stating that You changed the files and
#
# (c) You must retain, in the Source form of any Derivative Works
#     that You distribute, all copyright, patent, trademark, and
#     attribution notices from the Source form of the Work,
#     excluding those notices that do not pertain to any part of
#     the Derivative Works and
#
# (d) If the Work includes a "NOTICE" text file as part of its
#     distribution, then any Derivative Works that You distribute must
#     include a readable copy of the attribution notices contained
#     within such NOTICE file, excluding those notices that do not
#     pertain to any part of the Derivative Works, in at least one
#     of the following places: within a NOTICE text file distributed
#     as part of the Derivative Works within the Source form or
#     documentation, if provided along with the Derivative Works or,
#     within a display generated by the Derivative Works, if and
#     wherever such third-party notices normally appear. The contents
#     of the NOTICE file are for informational purposes only and
#     do not modify the License. You may add Your own attribution
#     notices within Derivative Works that You distribute, alongside
#     or as an addendum to the NOTICE text from the Work, provided
#     that such additional attribution notices cannot be construed
#     as modifying the License.
#
# You may add Your own copyright statement to Your modifications and
# may provide additional or different license terms and conditions
# for use, reproduction, or distribution of Your modifications, or
# for any such Derivative Works as a whole, provided Your use,
# reproduction, and distribution of the Work otherwise complies with
# the conditions stated in this License.


set(LIBDENG_TARGET "deng")



# Check if the surface will be X11 or WIN32
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(__SURFACE_SRC_FILE "src/deng/x11_surface.c")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(__SURFACE_SRC_FILE "src/deng/win32_surface.c")
endif()


# Set DENG core source files
set (
    LIBDENG_CORE_SRC_LIST
    src/deng/camera.cpp
    src/deng/cdeng.cpp
    src/deng/deng_math.cpp
    src/deng/key_ev.c
    src/deng/key_translation.c
    src/deng/renderer.cpp
    src/deng/window.cpp
    ${__SURFACE_SRC_FILE}
)


# Vulkan sources list
set (
    LIBDENG_VULKAN_SRC_LIST
    src/deng/vulkan/vulkan_dc.cpp
    src/deng/vulkan/vulkan_desc_c.cpp
    src/deng/vulkan/vulkan_handler.c
    src/deng/vulkan/vulkan_ic.cpp
    src/deng/vulkan/vulkan_pipelines.cpp
    src/deng/vulkan/vulkan_qm.cpp
    src/deng/vulkan/vulkan_ra.cpp
    src/deng/vulkan/vulkan_renderer.cpp
    src/deng/vulkan/vulkan_resources.cpp
    src/deng/vulkan/vulkan_scc.cpp
    src/deng/vulkan/vulkan_sd.cpp
)


# Set DENGUI source files
set (
    LIBDENG_DENGUI_SRC_LIST
    src/dengui/dengui_child.cpp
    src/dengui/dengui_events.cpp
    src/dengui/dengui_window.cpp
    src/dengui/map_editor_ui.cpp
    src/dengui/ui_callbacks.cpp
)


# Set all utilility source files
set (
    LIBDENG_UTIL_SRC_LIST
    collision.cpp
    font.cpp
    grid_generator.cpp
    shapes.cpp
    timer.cpp
)

# Set the main DENG sources list
set (
    LIBDENG_SRC_LIST
    ${LIBDENG_CORE_SRC_LIST}
    ${LIBDENG_VULKAN_SRC_LIST}
    ${LIBDENG_DENGUI_SRC_LIST}
    ${LIBDENG_UTIL_SRC_LIST}
)

if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set (
        __LIBDENG_DEPS
        ${LIBFREETYPE}
        ${LIBVULKAN}
        pthread
        X11
        Xcursor
        dl
    )
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set (
        __LIBDENG_DEPS
        ${LIBFREETYPE}
        ${LIBVULKAN}
        comctl32
        vulkan-1
    )
endif()


# Libdeng building function
function(BuildLibdeng) 
    add_library (
        ${LIBDENG_TARGET} SHARED
        ${LIBDENG_SRC_LIST}
    )

    target_include_directories (
        ${LIBDENG_TARGET}
        PUBLIC ${LIBFREETYPE_INCLUDE_PATH}
        PUBLIC ${VULKAN_INCLUDE_PATH}
    )

    target_link_libraries (
        ${LIBDENG_TARGET}
        ${__LIBDENG_DEPS}
    )
endfunction()
