/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __KEY_EV_C
#include <deng/surface/key_ev.h>


/// Create new input bitmask from multiple input events
deng_InputBits deng_CreateInputMask(deng_ui32_t ev_c, ...) {
    deng_InputBits bits = 0;
    va_list args;
    va_start(args, ev_c);

    if(ev_c > 8)
        RUN_ERR("deng_CreateInputMask", "Cannot have more than 8 input events!");

    for(deng_ui32_t i = 0; i < 8; i++) {
        if(i < ev_c)
            bits |= va_arg(args, deng_ui32_t);
        else bits |= DENG_KEY_UNKNOWN;

        if(i != 7) bits = bits << 8;
    }

    return bits;
}


/// Unmask deng_InputBits instance and return array
/// of deng_InputEv, whose size is exactly 8.
/// NOTE: Array elements that have no event index attached use DENG_KEY_UNKNOWN as a value
deng_InputEv *deng_UnmaskInput(deng_InputBits bits) {
    static deng_InputEv out_ev[8];
    deng_ui32_t ev = DENG_KEY_UNKNOWN;

    for(deng_i32_t i = 7; i >= 0; i--) {
        // If not the last index, shift input bits right
        if(i != 7) bits = bits >> 8;

        // Perform event id unmasking 
        ev = bits & 0b11111111;

        if(ev >= DENG_KEY_UNKNOWN && ev <= DENG_KEY_MENU)
            out_ev[i].key = ev;
        else if(ev >= DENG_MOUSE_BTN_UNKNOWN && ev <= DENG_MOUSE_SCROLL_UP)
            out_ev[i].btn = ev;
        else if(ev >= DENG_MOUSE_DELTA_UNKNOWN && ev <= DENG_MOUSE_DELTA_NY)
            out_ev[i].md_mov = ev;
    }

    return out_ev;
}


/// Register new keyevent to key register
/// This function is meant to be called only by DENG platform dependant surface instances
void __deng_RegisterKeyEvent (
    deng_Key key, 
    deng_MouseButton btn, 
    deng_InputType in_type, 
    deng_InputEventType ev_type
) {
    if(in_type == DENG_INPUT_TYPE_KB) {
        if(key == DENG_KEY_UNKNOWN) return;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE) {
            active_ev[key] = true;
            released_ev[key] = false;
        }
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED) {
            active_ev[key] = false;
            released_ev[key] = true;
        }
    }

    else if(in_type == DENG_INPUT_TYPE_MOUSE) {
        if(btn == DENG_MOUSE_BTN_UNKNOWN) return;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE) {
            active_ev[btn] = true;
            released_ev[btn] = false;
        }
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED) {
            active_ev[btn] = false;
            released_ev[btn] = true;
        }
    }
}


/// Find given key or mouse button status from specified event array
deng_bool_t __deng_FindKeyStatus (
    deng_Key key, 
    deng_MouseButton btn, 
    deng_InputType in_type, 
    deng_InputEventType ev_type
) {
    deng_bool_t stat = false;
    if(in_type == DENG_INPUT_TYPE_KB) {
        if(key == DENG_KEY_UNKNOWN)
            return false;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE)
            stat = active_ev[key];
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED)
            stat = released_ev[key];
    }

    else if(in_type == DENG_INPUT_TYPE_MOUSE) {
        if(btn == DENG_MOUSE_BTN_UNKNOWN)
            return false;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE)
            stat = active_ev[btn];
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED)
            stat = released_ev[btn];
    }

    return stat;
}


/// Clean released key and mouse button array 
void __deng_UnreleaseKeys() {
    memset(released_ev, 0x00, C_ARR_SIZE(released_ev));
    memset(released_ev, 0x00, C_ARR_SIZE(released_ev));
}
