/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __KEY_EV_C
#include <deng/key_ev.h>


void deng_RegisterKeyEvent (
    deng_Key key, 
    deng_MouseButton btn, 
    deng_InputType in_type, 
    deng_InputEventType ev_type
) {
    if(in_type == DENG_INPUT_TYPE_KB) {
        if(key == DENG_KEY_UNKNOWN) 
            return;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE) {
            active_keys[key] = true;
            released_keys[key] = false;
        }
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED) {
            active_keys[key] = false;
            released_keys[key] = true;
        }
    }

    else if(in_type == DENG_INPUT_TYPE_MOUSE) {
        if(btn == DENG_MOUSE_BTN_UNKNOWN)
            return;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE) {
            active_btns[btn] = true;
            released_btns[btn] = false;
        }
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED) {
            active_btns[btn] = false;
            released_btns[btn] = true;
        }
    }
}


/*
 * Find given key or mouse button status from specified event array
 */
deng_bool_t deng_FindKeyStatus (
    deng_Key key, 
    deng_MouseButton btn, 
    deng_InputType in_type, 
    deng_InputEventType ev_type
) {
    deng_bool_t stat = false;
    if(in_type == DENG_INPUT_TYPE_KB) {
        if(key == DENG_KEY_UNKNOWN)
            return false;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE)
            stat = active_keys[key];
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED)
            stat = released_keys[key];
    }
    else if(in_type == DENG_INPUT_TYPE_MOUSE) {
        if(btn == DENG_MOUSE_BTN_UNKNOWN)
            return false;
        if(ev_type == DENG_INPUT_EVENT_TYPE_ACTIVE)
            stat = active_btns[btn];
        else if(ev_type == DENG_INPUT_EVENT_TYPE_RELEASED)
            stat = released_btns[btn];
    }

    return stat;
}


void deng_UnreleaseKeys() {
    memset (
        released_keys, 
        0x00, 
        C_ARR_SIZE(released_keys)
    );
    memset (
        released_btns, 
        0x00, 
        C_ARR_SIZE(released_btns)
    );
}
