/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */


#define __DAS_STATIC_ASSEMBLER_C
#include <data/das_static_assembler.h>


/***********************************/
/**** Header assembly functions ****/
/***********************************/

/*
 * Assemble the info header of the asset
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleINFO_HDR(das_AssetMode dst_mode) {
    char *uuid = uuid_Generate();
    das_INFO_HDR inf_hdr = { 
        .magic_number = __DAS_STATIC_MAGIC_NUMBER,
        .hdr_name = __DAS_INFO_HEADER_NAME_NN, 
        .hdr_size = __DAS_INFO_HEADER_SIZE,
        .uuid = { 0 },
        .time_st = (deng_ui64_t) time(NULL),
        .asset_type = dst_mode,

        // Temporary
        .cmpr = 0
    };

    strncpy(inf_hdr.uuid, uuid, __DAS_UUID_LEN);
    inf_hdr.asset_type = dst_mode;

    fwrite(&inf_hdr, sizeof(das_INFO_HDR), 1, __wfile);
}


/*
 * Assemble vertex header of the asset
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleVERT_HDR(das_VertDynamic vert, das_AssetMode dst_mode) {
    das_VERT_HDR vert_hdr = {
        .hdr_name = __DAS_VERTICES_HEADER_NAME_NN
    };

    // Check the vertices' destination mode for calculating the header size
    switch(dst_mode) {
    case __DAS_ASSET_MODE_3D_UNMAPPED_UNOR:
        vert_hdr.hdr_size = sizeof(__das_VertTemplate) + vert.v3d.pn * sizeof(das_ObjPosData) + 28;
        break;

    case DAS_ASSET_MODE_3D_UNMAPPED:
        // Store only vertex position data
        vert_hdr.hdr_size = 2 * sizeof(__das_VertTemplate) + vert.v3d.pn * sizeof(das_ObjPosData) + 
            vert.v3d.nn + sizeof(das_ObjNormalData) + 28;
        break;

    case __DAS_ASSET_MODE_3D_TEXTURE_MAPPED_UNOR:
        vert_hdr.hdr_size = 2 * sizeof(__das_VertTemplate) + vert.v3d.pn * (sizeof(das_ObjPosData) + 
            vert.v3d.tn * sizeof(das_ObjTextureData)) + 28;
        break;

    case DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
        vert_hdr.hdr_size = 3 * sizeof(__das_VertTemplate) + vert.v3d.pn * sizeof(das_ObjPosData) + 
            vert.v3d.tn * sizeof(das_ObjTextureData) + vert.v3d.nn * sizeof(das_ObjNormalData) + 28;
        break;

    default:
        break;
    }

    // Write vertices header data into stream
    fwrite(&vert_hdr, sizeof(das_VERT_HDR), 1, __wfile);

    // Check which subheaders to build
    __das_AssembleVPOS_HDR(&vert);
    switch(dst_mode) {
    case DAS_ASSET_MODE_3D_UNMAPPED:
        __das_AssembleVNOR_HDR(&vert);
        break;

    case __DAS_ASSET_MODE_3D_TEXTURE_MAPPED_UNOR:
        __das_AssembleVTEX_HDR(&vert);
        break;

    case DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
        __das_AssembleVTEX_HDR(&vert);
        __das_AssembleVNOR_HDR(&vert);
        break;

    default:
        break;
    }
}


/*
 * Assemble vertex position subheader
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleVPOS_HDR(das_VertDynamic *p_vert) {
    das_VPOS_HDR vpos_hdr = {
        .hdr_name = __DAS_VERT_POSITION_HEADER_NAME_NN,
        .vert_c = p_vert->v3d.pn,
        .hdr_size = p_vert->v3d.pn * sizeof(das_ObjPosData) + 16
    };

    // Write the header beginning to stream
    fwrite(&vpos_hdr, sizeof(das_VPOS_HDR), 1, __wfile);

    // Write vertices data to the stream
    fwrite(p_vert->v3d.pos, sizeof(das_ObjPosData), vpos_hdr.vert_c, __wfile);
}


/*
 * Assemble texture position subheader
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleVTEX_HDR(das_VertDynamic *p_vert) { 
    das_VTEX_HDR vtex_hdr = {
        .hdr_name = __DAS_TEX_POSITION_HEADER_NAME_NN,
        .vert_c = p_vert->v3d.tn,
        .hdr_size = p_vert->v3d.tn * sizeof(das_ObjTextureData) + 16
    };
    
    // Write the header beginning to stream
    fwrite(&vtex_hdr, sizeof(das_VTEX_HDR), 1, __wfile);

    // Write vertices data to the stream
    fwrite(p_vert->v3d.tex, sizeof(das_ObjTextureData), vtex_hdr.vert_c, __wfile);
}


/*
 * Assemble texture position subheader
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleVNOR_HDR(das_VertDynamic *p_vert) { 
    das_VTEX_HDR vnor_hdr = {
        .hdr_name = __DAS_NORM_POSITION_HEADER_NAME_NN,
        .vert_c = p_vert->v3d.nn,
        .hdr_size = p_vert->v3d.nn * sizeof(das_ObjNormalData) + 16
    };
    
    // Write the header beginning to stream
    fwrite(&vnor_hdr, sizeof(das_VNOR_HDR), 1, __wfile);

    // Write vertices data to the stream
    fwrite(p_vert->v3d.norm, sizeof(das_ObjNormalData), vnor_hdr.vert_c, __wfile);
}

    
/*
 * Assemble META_HDR with additional meta data 
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleMETA_HDR(char *meta_data) {
    das_META_HDR meta_hdr = {
        .beg = __DAS_META_HEADER_NAME,
        .hdr_size = 16 + strlen(meta_data),
        .data_size = strlen(meta_data),
        .data = meta_data,
    };

    
    // Write the first part of the header into the stream
    fwrite(&meta_hdr, 8, 2, __wfile);

    // Write metadata into the stream
    fwrite(meta_hdr.data, sizeof(char), strlen(meta_hdr.data), __wfile);
}


/*
 * Assemble indices header of the asset
 * This function call assumes that __wfile is a valid pointer to a stream
 */
static void __das_AssembleINDX_HDR(das_IndicesDynamic inds, das_AssetMode am) {
    // 
    das_INDX_HDR indx_hdr = {
        .hdr_name = __DAS_INDICES_HEADER_NAME,
        .hdr_size = (deng_ui32_t) (16 + inds.n * sizeof(deng_ui32_t)),
        .ind_c = (deng_ui32_t) inds.n
    };

    // Write the header into the stream
    fwrite(&indx_hdr, sizeof(das_INDX_HDR), 1, __wfile);

    // Write position indices array into the stream
    fwrite(inds.pos, sizeof(deng_ui32_t), inds.n, __wfile);

    // Write position indices array into the stream
    if(am == __DAS_ASSET_MODE_3D_TEXTURE_MAPPED_UNOR || 
       am == DAS_ASSET_MODE_3D_TEXTURE_MAPPED)
        fwrite(inds.tex, sizeof(deng_ui32_t), inds.n, __wfile);

    // Write position indices array into the stream
    if(am == DAS_ASSET_MODE_3D_UNMAPPED ||
       am == DAS_ASSET_MODE_3D_TEXTURE_MAPPED)
        fwrite(inds.norm, sizeof(deng_ui32_t), inds.n, __wfile);
}


/*
 * Open new file stream for writing 
 */
static void __das_OpenFileStream(char *file_name) {
    __wfile = fopen(file_name, "wb");
    if(!__wfile)
        FILE_ERR(file_name);
}


/*
 * Close the current file stream
 */
static void __das_CloseFileStream() {
    if(__wfile) {
        fclose(__wfile);
        __wfile = NULL;
    }
}


/*
 * Assemble static DENG asset from das_Asset instance
 */
void das_StaticAssemble (
    das_Asset *p_asset,
    char *file_name,
    char **meta_data,
    size_t meta_c
) {
    __das_OpenFileStream(file_name);

    // Assemble INFO_HDR
    __das_AssembleINFO_HDR(p_asset->asset_mode);

    // Check for any metadata and write it to the stream if it exists
    for(size_t i = 0; i < meta_c; i++)
        __das_AssembleMETA_HDR(meta_data[i]);

    // Assemble VERT_HDR
    __das_AssembleVERT_HDR(p_asset->vertices, p_asset->asset_mode);

    // Assemble INDX_HDR
    __das_AssembleINDX_HDR(p_asset->indices, p_asset->asset_mode);
    __das_CloseFileStream();
}

