/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __DAS_READER_C
#include <data/das_reader.h>


/* 
 * Read .das binary asset file into das_Asset instance
 */
void das_LoadAsset (
    das_Asset *p_asset, 
    das_AssetMode dst_mode,
    das_ObjColorData color,
    deng_bool_t read_meta,
    char *tex_uuid,
    char *file_name
) {
    p_asset->tex_uuid = tex_uuid;
    p_asset->color = color;
    p_asset->is_shown = true;
    p_asset->force_unmap = false;

    // Write all file contents into a buffer
    __das_ReadAssetFile((char*) file_name);

    das_INFO_HDR inf_hdr = {0};
    das_VERT_HDR vert_hdr = {0};
    das_INDX_HDR indx_hdr = {0};

    __das_ReadINFO_HDR (
        &inf_hdr,
        file_name
    );

    // Copy uuid from read info header instance to asset uuid instance
    p_asset->uuid = (char*) calloc(__DAS_UUID_LEN + 1, sizeof(char));
    strcpy(p_asset->uuid, inf_hdr.uuid);

    // Check if metadata should be read or ignored
    if(read_meta)
        __das_ReadMeta();
    else __das_SkipMetaHeaders();

    __das_ReadVERT_HDR (
        &vert_hdr,
        file_name
    );

    p_asset->vertices.n = vert_hdr.vert_c;

    __das_CopyVertices (
        p_asset,
        inf_hdr.asset_type,
        file_name
    );

    __das_ReadINDX_HDR (
        &indx_hdr,
        file_name
    );

    p_asset->indices.n = indx_hdr.ind_c;

    __das_CopyIndices (
        &p_asset->indices.indices,
        indx_hdr.ind_c,
        file_name
    );

    // Check if vertices are unnormalised and if they are then normalise
    if(inf_hdr.asset_type == __DAS_ASSET_MODE_3D_UNMAPPED_UNOR ||
       inf_hdr.asset_type == __DAS_ASSET_MODE_3D_TEXTURE_MAPPED_UNOR) {
        __das_VertNormalise(p_asset);
    }

    __das_ReadCleanup();
}


/*
 * Get all the metadata which was read from the last read_meta specified
 * das_LoadAsset call
 */
char **das_GetMeta(size_t *p_meta_c) {
    *p_meta_c = __meta_c;
    return __meta_infos;
}


/*
 * Clean all memory allocated for meta data
 */
void das_CleanMeta() {
    for(size_t i = 0; i < __meta_c; i++)
        free(__meta_infos[i]);

    if(__meta_c) {
        free(__meta_infos);
        __meta_infos = NULL;
        __meta_c = 0;
    }
}


/**********************************************/
/********** Header reading functions **********/
/**********************************************/

/* 
 * Read asset information from INFO_HDR
 */
void __das_ReadINFO_HDR (
    das_INFO_HDR *out_hdr,
    char *file_name
) {
    das_ErrBufferReadCheck(__offset + sizeof(das_INFO_HDR), __buf_size, file_name);

    // INFO_HDR is always the first header in .das file
    memcpy(out_hdr, __cbuf + __offset, sizeof(das_INFO_HDR));
    __offset += sizeof(das_INFO_HDR);

    // Copy header name into larger array for verification purposes
    char pad_name[9] = {0};
    strncpy(pad_name, out_hdr->hdr_name, 8);

    // Verify that file magic's number matches any of the supported format magic numbers
    if(das_MagicNumberCheck(out_hdr->magic_number) == DAS_ERROR_INVALID_MAGIC_NUMBER)
        __DAS_READ_INVALID_MAGIC_NUM(file_name);

    // Verify info header integrity
    if(strcmp(pad_name, __DAS_INFO_HEADER_NAME) || out_hdr->cmpr) 
        __DAS_READ_CORRUPT_ERROR(file_name);
}


/*
 * Verify that all custom headers are skipped from reading
 */
void __das_SkipMetaHeaders(char *file_name) {
    deng_ui32_t *indices;
    deng_ui32_t ind_c = 0; 

    // Find all instances for custom header beginnings
    cm_FindnAllSubstrings (
        __cbuf,
        __buf_size,
        __DAS_META_HEADER_NAME,
        strlen(__DAS_META_HEADER_NAME),
        &indices,
        &ind_c
    ); 

    printf("ind_c: %d\n", ind_c);
    if(ind_c) {
        __offset = indices[ind_c - 1];
        deng_ui32_t hdr_size = 0;

        // Buffer bounds check
        das_ErrBufferReadCheck(__offset + sizeof(deng_ui32_t) + 8, __buf_size, file_name);
        memcpy(&hdr_size, __cbuf + __offset + 8, sizeof(deng_ui32_t));
        das_ErrBufferReadCheck(hdr_size, __buf_size, file_name);

        printf("hdr_size: %d\n", hdr_size);
        __offset += hdr_size;
        free(indices);
    }
}


/*
 * Read meta information contained between BEG_HDR and END_HDR
 * This function returns pointer to heap allocated memory, manual cleanup is necessary
 */
void __das_ReadMeta() {
    // Check if previous metadata has been allocated and if it has 
    // then perform cleanup
    if(__meta_c && __meta_infos) {
        for(size_t i = 0; i < __meta_c; i++)
            free(__meta_infos[i]);
        free(__meta_infos);

        __meta_infos = NULL;
        __meta_c = 0;
    }

    deng_ui32_t *indices = NULL;
    deng_ui32_t ind_c = 0;
    
    // Find all instances of custom headers
    cm_FindnAllSubstrings (
        __cbuf,
        __buf_size,
        __DAS_META_HEADER_NAME,
        strlen(__DAS_META_HEADER_NAME),
        &indices,
        &ind_c
    );

    __meta_c = (deng_ui64_t) ind_c;
    __meta_infos = (char**) malloc(ind_c * sizeof(char*));

    for(deng_ui32_t i = 0; i < __meta_c; i++) {
        // Skip header size reading and read data size directly
        __offset = indices[i] + 12;
        deng_ui32_t data_len = 0;
        memcpy(&data_len, __cbuf + __offset, sizeof(deng_ui32_t));
        
        // Copy all metadata information to __meta_infos buffer
        __offset += 4;
        __meta_infos[i] = (char*) calloc(data_len + 1, sizeof(char));
        memcpy(__meta_infos[i], __cbuf + __offset, data_len * sizeof(char));
        
        __offset += data_len;
    }
}

/*
 * Read asset information from VERT_HDR
 */
void __das_ReadVERT_HDR (
    das_VERT_HDR *out_hdr,
    char *file_name
) {
    if(__offset + sizeof(das_VERT_HDR) >= __buf_size)
        __DAS_READ_CORRUPT_ERROR(file_name);

    // Copy the first part of the buffer into das_VERT_HDR struct
    memcpy (
        out_hdr, 
        __cbuf + __offset, 
        sizeof(das_VERT_HDR)
    );
    __offset += sizeof(das_VERT_HDR);

    char pad_hdr[9] = {0};
    strncpy(pad_hdr, out_hdr->hdr_name, 8);

    // Check if header name is correct
    if(strcmp(pad_hdr, __DAS_VERTICES_HEADER_NAME))
        __DAS_READ_CORRUPT_ERROR(file_name);
}


/*
 * Read asset information from INDX_HDR
 */
void __das_ReadINDX_HDR (
    das_INDX_HDR *out_hdr,
    char *file_name
) {
    if(__offset + sizeof(das_INDX_HDR) >= __buf_size)
        __DAS_READ_CORRUPT_ERROR(file_name);


    memcpy (
        out_hdr, 
        __cbuf + __offset, 
        sizeof(das_INDX_HDR)
    );

    __offset += sizeof(das_INDX_HDR);

    char pad_hdr[9] = {0};
    strncpy(pad_hdr, out_hdr->hdr_name, 8);

    // Check if header name is correct
    if(strcmp(pad_hdr, __DAS_INDICES_HEADER_NAME)) 
        __DAS_READ_CORRUPT_ERROR(file_name);
}


/*
 * Read all data from asset file into buffer for reading
 */
void __das_ReadAssetFile(char *file_name) {
    FILE *file;
    __offset = 0;
    file = fopen(file_name, "rb");

    if(!file) FILE_ERR(file_name);

    fseek(file, 0, SEEK_END);
    __buf_size = ftell(file);
    fseek(file, 0, SEEK_SET);

    __cbuf = (char*) calloc (
        __buf_size + 1,
        sizeof(char)
    );

    size_t res = fread(__cbuf, sizeof(char), __buf_size, file);
    if(!res) FILE_ERR(file_name);

    fclose(file);
}


/*
 * Free all resources allocated in asset reading 
 */
void __das_ReadCleanup() {
    free(__cbuf);
}


/*
 * Allocate memory for vertices
 */
void __das_AllocVertMem (
    das_Asset *p_asset,
    das_AssetMode src_mode,
    deng_bool_t *p_skip_tex
) {
    switch(p_asset->asset_mode)
    {
    case DAS_ASSET_MODE_3D_UNMAPPED:
    DAS_ASSET_MODE_3D_UNMAPPED:
        p_asset->vertices.uni_vert.vun = (VERT_UNMAPPED*) calloc (
            p_asset->vertices.n,
            sizeof(VERT_UNMAPPED)
        );
        
        *p_skip_tex = true;
        break;

    case DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
    DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
        p_asset->vertices.uni_vert.vmn = (VERT_MAPPED*) calloc (
            p_asset->vertices.n,
            sizeof(VERT_MAPPED)
        );

        *p_skip_tex = false;
        break;

    case DAS_ASSET_MODE_UNDEFINED:
        // Allocate memory according to src_mode
        switch(src_mode)
        {
        case DAS_ASSET_MODE_3D_UNMAPPED:
            goto DAS_ASSET_MODE_3D_UNMAPPED;
            break;

        case DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
            goto DAS_ASSET_MODE_3D_TEXTURE_MAPPED;
            break;
        default:
            break;
        }
        break;

    default:
        break;
    }
}


/*
 * Copy asset vertices from buffer to out_vert
 * This functions assumes that the p_asset has correct vertices count set and
 * the offset is at the beginning of vertex data sequence
 */
void __das_CopyVertices (
    das_Asset *p_asset,
    das_AssetMode src_mode,
    char *file_name
) {
    // Check if the source mode is unnormalised and if it is then perform copy and return
    if(src_mode == __DAS_ASSET_MODE_3D_UNMAPPED_UNOR) {
        das_ErrBufferReadCheck(p_asset->vertices.n * sizeof(__VERT_UNMAPPED_UNOR), __buf_size, file_name);

        p_asset->vertices.uni_vert.vuu = (__VERT_UNMAPPED_UNOR*) calloc (
            p_asset->vertices.n,
            sizeof(__VERT_UNMAPPED_UNOR)
        );

        memcpy (
            p_asset->vertices.uni_vert.vuu,
            __cbuf,
            sizeof(__VERT_UNMAPPED_UNOR) * p_asset->vertices.n
        );

        return;
    }

    else if(src_mode == __DAS_ASSET_MODE_3D_TEXTURE_MAPPED_UNOR) {
        das_ErrBufferReadCheck(p_asset->vertices.n * sizeof(__VERT_MAPPED_UNOR), __buf_size, file_name);

        p_asset->vertices.uni_vert.vuu = (__VERT_UNMAPPED_UNOR*) calloc (
            p_asset->vertices.n,
            sizeof(__VERT_MAPPED_UNOR)
        );

        memcpy (
            p_asset->vertices.uni_vert.vuu,
            __cbuf,
            sizeof(__VERT_MAPPED_UNOR) * p_asset->vertices.n
        );

        return;
    }


    deng_bool_t skip_tex = false;

    // Allocate memory for vertices
    __das_AllocVertMem (
        p_asset,
        src_mode,
        &skip_tex
    );

    // Copy all data from buffer to out_vert
    switch(src_mode) 
    {
    case DAS_ASSET_MODE_3D_UNMAPPED:
        das_ErrBufferReadCheck(sizeof(VERT_UNMAPPED) * p_asset->vertices.n, __buf_size, file_name);

        // Destination vertex is VERT_UNMAPPED
        if(skip_tex) {
            memcpy (
                p_asset->vertices.uni_vert.vun,
                __cbuf + __offset,
                sizeof(VERT_UNMAPPED) * p_asset->vertices.n
            );

            __offset += sizeof(VERT_UNMAPPED) * p_asset->vertices.n;
        }

        else __DAS_READ_INVALID_VERT_FORMAT(file_name);
        break;

    case DAS_ASSET_MODE_3D_TEXTURE_MAPPED:
        das_ErrBufferReadCheck(sizeof(__VERT_MAPPED_UNOR) * p_asset->vertices.n, __buf_size, file_name);

        // Destination vertex is VERT_MAPPED_NOR
        if(!skip_tex) {
            memcpy (
                p_asset->vertices.uni_vert.vmn,
                __cbuf + __offset,
                sizeof(VERT_MAPPED) * p_asset->vertices.n
            );

            __offset += sizeof(VERT_MAPPED) * p_asset->vertices.n;
        }

        // Destination vertex is VERT_UNMAPPED
        else {
            // Allocate temporary buffer for storing vertices
            VERT_MAPPED *tmp = (VERT_MAPPED*) calloc (
                p_asset->vertices.n,
                sizeof(VERT_MAPPED)
            );

            memcpy (
                tmp,
                __cbuf + __offset,
                sizeof(VERT_MAPPED) * p_asset->vertices.n
            );

            __offset += sizeof(VERT_MAPPED) * p_asset->vertices.n;
            for(size_t i = 0; i < p_asset->vertices.n; i++) {
                p_asset->vertices.uni_vert.vun[i].vert_data = tmp[i].vert_data;
                p_asset->vertices.uni_vert.vun[i].norm_data = tmp[i].norm_data;
            }

            free(tmp);
        }
        break;

    default: 
        break;
    }
}


/*
 * Copy all indices from buffer to p_out_ind
 * This function allocates memory and copies 
 * the data from file buffer to *p_out_ind
 */
void __das_CopyIndices (
    deng_ui32_t **p_out_ind,
    deng_ui32_t ind_c,
    char *file_name
) {
    das_ErrBufferReadCheck(ind_c * sizeof(deng_ui32_t), __buf_size, file_name);

    (*p_out_ind) = (deng_ui32_t*) calloc (
        ind_c,
        sizeof(deng_ui32_t)
    );

    memcpy (
        (*p_out_ind),
        __cbuf + __offset,
        ind_c * sizeof(deng_ui32_t) 
    );

    __offset += ind_c * sizeof(deng_ui32_t);
}



/*
 * Increment the reading offset by n bytes
 */
void __das_IncrementOffset(size_t n) {
    __offset += n;
}


/*******************************************************************/
/*********** Vertex normal calculation algorithm functions *********/
/*******************************************************************/

/*
 * Create vertex normals for vertices that are not normalised
 * and add them to closest 
 */
static void __das_VertNormalise(das_Asset *p_asset) {
    // Allocate memory for appropriate 
    /*switch(p_asset->asset_mode) {*/
    /*case __DAS_ASSET_MODE_3D_UNMAPPED_UNOR:*/
        /*p_asset->vertices.uni_vert.vun = (VERT_UNMAPPED*) calloc (*/
            /*p_asset->vertices.n,*/
            /*sizeof(VERT_UNMAPPED)*/
        /*);*/
        /*break;*/
    /*}*/
}
