/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */


#define __DAS_CHECK_C
#include <data/das_check.h>


/// Check if the requested memory size is available for reading otherwise
/// throw a runtime error
void das_ErrBufferReadCheck (
    size_t req_size, 
    size_t max_size,
    const char *file_name
) {
    if(req_size >= max_size) {
        fprintf(stdout, "Failed to read from file %s, possible file corruption\n", file_name);
        exit(DAS_ERROR_FILE_CORRUPTION);
    }
}


/// Check if the given header specifier is valid
void das_CheckHdrName(char *name, char *exp_name, const char *file_name) {
    // Copy the non null terminated name to bigger string
    char nname[9] = { 0 };
    strncpy(nname, name, 8);

    // Check if the name does not match the expected name
    if(strcmp(nname, exp_name))
        __DAS_READ_CORRUPT_ERROR(file_name);
}


/// Check if provided uuid is valid
das_Error das_UuidCheck(char *uuid) {
    // Check if UUID length is correct and separators are in correct places
    if(strlen(uuid) != __DAS_UUID_LEN || uuid[8] != '-' || 
       uuid[14] != '-' || uuid[19] != '-' || uuid[23] != '-' || uuid[27] != '-')
        return DAS_ERROR_INVALID_UUID;

    // Check each character in uuid sequence for any invalid characters
    for(size_t i = 0; i < strlen(uuid); i++) {
        if(i == 14 || i == 19 || i == 23 || i == 27) 
            continue;

        if((uuid[i] < '0' && uuid[i] > '9') && (uuid[i] < 'a' && uuid[i] > 'z') &&
           (uuid[i] < 'A' && uuid[i] > 'Z')) 
            return DAS_ERROR_INVALID_UUID;
    }

    return DAS_ERROR_SUCCESS;
}


/// Check if magic number provided is valid or not
das_Error das_MagicNumberCheck(deng_ui64_t num) {
    if(num != __DAS_STATIC_MAGIC_NUMBER && 
       num != __DAS_ANIMATION_MAGIC_NUMBER &&
       num != __DAS_MAP_MAGIC_NUMBER)
        return DAS_ERROR_INVALID_MAGIC_NUMBER;

    return DAS_ERROR_SUCCESS;
}
